version: "3"

services:
  investment-advisor-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - .:/app
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    restart: unless-stopped
